### ISSUE TITLE
Background image for for the footer renders too high on the page on mobile browsers

### ISSUE THREAD

**Issue by audreytoskin** [voiceofrae/RelaxIO#66] opened 2017-04-25 23:59 UTC
I've tested on Android (Samsung Galaxy S4) with both Firefox Beta and Google Chrome.

I would include a screenshot, but I'm having issues with my phone's USB debugger...

**Comment by docsmage** [comment] 2017-04-26 19:27
Thanks for filing - I also noticed this and filed the day of the release, #62.
Since this is a duplicate of #62, closing this one and keeping it open. Feel free to add notes or a screenshot there (I added one from my model, Samsung Galaxy s7 edge).

**Closed as completed by docsmage** 2017-04-26 19:27 UTC
